# Generated by Django 3.1.7 on 2021-02-22 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('semester_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_group_work', models.BooleanField()),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('total_score', models.PositiveIntegerField()),
                ('course', models.ManyToManyField(to='deliverables.Course')),
            ],
        ),
        migrations.CreateModel(
            name='DeliverableFileAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='deliverable-file-attachments/')),
                ('label', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='DeliverableLinkAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024)),
                ('label', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('user_type', models.CharField(choices=[('ST', 'Student'), ('PR', 'Professor')], max_length=2)),
                ('program', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliverableSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateTimeField(null=True)),
                ('score', models.PositiveIntegerField()),
                ('feedback', models.TextField(blank=True)),
                ('student_has_seen_feedback', models.BooleanField(default=False)),
                ('deliverable', models.ManyToManyField(to='deliverables.Deliverable')),
                ('file_attachments', models.ManyToManyField(to='deliverables.DeliverableFileAttachment')),
                ('group_members', models.ManyToManyField(related_name='deliverable_submission_group_members_set', to='deliverables.Profile')),
                ('link_attachments', models.ManyToManyField(to='deliverables.DeliverableLinkAttachment')),
                ('submitter', models.ManyToManyField(related_name='deliverable_submission_submitter_set', to='deliverables.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='deliverable',
            name='file_attachments',
            field=models.ManyToManyField(to='deliverables.DeliverableFileAttachment'),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='link_attachments',
            field=models.ManyToManyField(to='deliverables.DeliverableLinkAttachment'),
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_professor_set', to='deliverables.profile'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='course_student_set', to='deliverables.Profile'),
        ),
    ]
